---
- name: Templates directory
  file:
      state: directory
      path: "{{ template_path }}"
- name: Retrieve cloud-init images
  get_url:
      url: "{{ item.repo | default( 'https://cloud-images.ubuntu.com' ) }}/{{ item.codename | default( 'focal' ) }}/{{ item.version | default( 'current' ) }}/{{ item.codename | default( 'focal' ) }}-server-cloudimg-{{ item.arch | default( 'amd64' ) }}.img"
      dest: "{{ template_path }}/{{ item.filename }}"
  when: item.type == "Ubuntu" or item.type == "Debian"
  with_items: "{{ cloud_images }}"
  register: downloaded
