---
- name: Templates directory
  file:
      state: directory
      path: "{{ template_path }}"
- name: Retrieve Ubuntu cloud-init images
  get_url:
      url: "{{ item.repo | default( 'https://cloud-images.ubuntu.com' ) }}/{{ item.codename | default( 'focal' ) }}/{{ item.version | default( 'current' ) }}/{{ item.codename | default( 'focal' ) }}-server-cloudimg-{{ item.arch | default( 'amd64' ) }}.img"
      dest: "{{ template_path }}/{{ item.filename }}"
  when: item.type == "Ubuntu"
  with_items: "{{ cloud_images }}"
  register: downloaded
- name: Retrieve Minimal Ubuntu cloud-init images
  get_url:
      url: "{{ item.repo | default( 'https://cloud-images.ubuntu.com/minimal/releases' ) }}/{{ item.codename | default( 'focal' ) }}/{{ item.version | default( 'release' ) }}/ubuntu-{{ item.majorver }}-minimal-cloudimg-{{ item.arch | default( 'amd64' ) }}.img"
      dest: "{{ template_path }}/{{ item.filename }}"
  when: item.type == "Ubuntu-minimal"
  with_items: "{{ cloud_images }}"
  register: downloaded
- name: Retrieve Debian cloud-init images
  get_url:
      url: "{{ item.repo | default( 'https://cdimage.debian.org/cdimage/cloud' ) }}/{{ item.codename | default( 'buster' ) }}/{{ item.version | default( 'current' ) }}/debian-10-nocloud-{{ item.arch | default( 'amd64' ) }}-{{ item.version }}.qcow2"
      dest: "{{ template_path }}/{{ item.filename }}"
  when: item.type == "Debian"
  with_items: "{{ cloud_images }}"
  register: downloaded
- name: Retrieve Fedora cloud-init images
  get_url:
      url: "{{ item.repo | default( 'https://download.fedoraproject.org/pub/fedora/linux/releases' ) }}/{{ item.version | default( '32' ) }}/Cloud/{{ item.arch | default( 'x86_64' ) }}/images/Fedora-Cloud-Base-{{ item.version | default('32') }}-{{ item.build | default('1.6') }}.{{ item.arch | default('x86_64') }}.qcow2"
      dest: "{{ template_path }}/{{ item.filename }}"
  when: item.type == "Fedora"
  with_items: "{{ cloud_images }}"
  register: downloaded
- name: Retrieve OpenSuSE cloud-init images
  get_url:
      url: "{{ item.repo | default( 'https://download.opensuse.org/repositories/Cloud:/Images:/Leap_{{ item.version | default('15.2' ) }}/images/openSUSE-Leap-{{ item.version | default('15.2') }}-OpenStack.{{ item.arch | default('x86_64') }}.qcow2"
      dest: "{{ template_path }}/{{ item.filename }}"
  when: item.type == "Fedora"
  with_items: "{{ cloud_images }}"
  register: downloaded
- name: Retrieve CentOS-8 cloud-init images
  get_url:
      url: "{{ item.repo | default( 'https://cloud.centos.org/centos/{{ item.version | default('8') }}/{{ item.arch | default('x86_64') }}/images/CentOS-{{ item.version | default('8') }}-GenericCloud-{{ item.build | default('8.2.2004-20200611.2') }}.{{ item.arch | default('x86_64') }}.qcow2"
      dest: "{{ template_path }}/{{ item.filename }}"
  when: item.type == "CentOS-8"
  with_items: "{{ cloud_images }}"
  register: downloaded
- name: Retrieve CentOS-7 cloud-init images
  get_url:
      url: "{{ item.repo | default( 'https://cloud.centos.org/centos/{{ item.version | default('7') }}/images/CentOS-{{ item.version | default('7') }}-{{ item.arch | default('x86_64') }}-GenericCloud-{{ item.build | default('2003') }}.qcow2"
      dest: "{{ template_path }}/{{ item.filename }}"
  when: item.type == "CentOS-7"
  with_items: "{{ cloud_images }}"
  register: downloaded
