---
- name: Cloud images directory
  file:
      path: "{{ image_repo_dir }}"
      state: directory
- name: Default images list
  set_fact:
      images: "{{ default_images }}"
  when: images is not defined
- name: Image tree
  file:
      path: "{{ image_repo_dir }}/{{ item.family }}/{{ item.label }}"
      state: directory
  when: item.label in images
  with_items:
      - "{{ cloud_images_list }}"
- name: Download images
  get_url:
      url: "{{ item.url }}"
      dest: "{{ image_repo_dir }}/{{ item.family }}/{{ item.label }}/{{ item.filename }}"
  when: item.label in images
  with_items:
      - "{{ cloud_images_list }}"
  register: downloaded
- name: Images list
  debug: var=images
- name: Downloaded images metadata
  copy:
      dest: "{{ image_repo_dir }}/metadata.json"
      content: "{{ downloaded }}"
